engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
  eslint:
    enabled: true
    config:
      extensions:
      - .es6
      - .js
      - .jsx

  ratings:
     paths:
     - "**.es6"
     - "**.js"
     - "**.coffee"
     - "**.jsx"
     - "**.rb"

  scsslint:
  csslint:
    enabled: true
exclude_paths:
  - vendor/**/*
